book/urls.py
from django.urls import path

from book.views import BookView, list_book

app_name = "book"

urlpatterns = [
    path("<int:book_id>", BookView.as_view(), name="get"),
    path("list", list_book, name="list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


# namespace is used to create url tags to be used in the html files
urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "financial_statement/",
        include("financial_statement.urls", namespace="financial_statement"),
    ),
    path("", include("core.urls", namespace="core")),
    path("valuation/", include("valuation.urls", namespace="valuation")),
    path("user/", include("user.urls", namespace="user")),
    path("company/", include("company.urls", namespace="company")),
    path("notification/", include("notification.urls", namespace="notification")),
    path("post/", include("post.urls", namespace="post")),
    path("book/", include("book.urls", namespace="book")),
]

core/urls.py
from django.urls import path

from core.views import home_view, landing_page_view, out_of_service

# This must be same as the namespace in the config.urls.py
# This allows this view to be used as a url tag in the html.
app_name = "core"

urlpatterns = [
    path("", landing_page_view, name="landing_page"),
    path("out_of_service/<str:service>", out_of_service, name="out_of_service"),
]

post/urls.py
from django.urls import path
from post.views import (
    LogView,
    PostView,
    list_post,
)

app_name = "post"

urlpatterns = [
    path("<int:post_id>", PostView.as_view(), name="get"),
    path("list", list_post, name="list"),
    path("logs", LogView.as_view(), name="logs"),
]

user/urls.py
from django.urls import path
from user.views import (
    UserView,
)

app_name = "user"

urlpatterns = [
    path("profile", UserView.as_view(), name="profile"),
]

templates/partials/footer.html
<footer class="px-10 border-t-2">
    <h4 class="text-md font-serif ml-10">&copy; Jiun Kim</h4> 
</footer>

templates/partials/nav.html
{%load static%}

<div>
    <a href="{% url "core:landing_page" %}" class="mr-6">
        <img class="w-24 mt-8 ml-16" src="{% static 'img/jiun2.png' %}" />
    </a>
</div>
<div>
    <ul class="flex .justify-between text-sm font-medium">
        <li class="ml-8"><a href="{% url "post:logs" %}">Posts</a></li>
        <li class="ml-8"><a href="{% url "post:list" %}">Logs</a></li>
        <li class="ml-8"><a href="{% url "book:list" %}">Books</a></li>
        <li class="ml-8"><a href="{% url "user:profile" %}">Weddew</a></li>
    </ul>
</div>