book/urls.py
from django.urls import path

from book.views import BookView, list_book

app_name = "book"

urlpatterns = [
    path("<int:book_id>", BookView.as_view(), name="get"),
    path("list", list_book, name="list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


# namespace is used to create url tags to be used in the html files
urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "financial_statement/",
        include("financial_statement.urls", namespace="financial_statement"),
    ),
    path("", include("core.urls", namespace="core")),
    path("valuation/", include("valuation.urls", namespace="valuation")),
    path("user/", include("user.urls", namespace="user")),
    path("company/", include("company.urls", namespace="company")),
    path("notification/", include("notification.urls", namespace="notification")),
    path("post/", include("post.urls", namespace="post")),
    path("book/", include("book.urls", namespace="book")),
]

book/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100, blank=False)
    writer = models.CharField(max_length=100, blank=False)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

book/views.py
from django.shortcuts import render
from book.models import Book
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.views import View
from django.http import Http404


def list_book(request):
    try:
        all_books = Book.objects.all().order_by("-created_at")
        page = int(request.GET.get("p", 1))  # 없으면 1로 지정
        paginator = Paginator(all_books, 5)  # 한 페이지 당 몇개 씩 보여줄 지 지정
        books = paginator.get_page(page)
    except Book.DoesNotExist:
        return redirect("404.html")

    context = {
        "books": books,
    }
    return render(request, "book/books.html", context=context)


class BookView(View):
    def get(self, request, book_id):
        try:
            book = Book.objects.get(id=book_id)
        except Book.DoesNotExist:
            raise Http404
        context = {
            "book": book,
        }
        return render(request, "book/book.html", context=context)

templates/book/book.html
{% extends "base.html" %}
{% block title %}
    post
{% endblock %}
{% block content %}

    <div class="flex justify-between px-20 py-10">
        <h4 class="text-2xl font-serif font-bold"> {{book.title}} </h4>
    </div>
    <section class="gap-4 px-20">
        <h4 class="font-thin font-mono">{{book.created_at}} by Jiun Kim</h4>
        <h4 class="text-m font-serif font-bold"> written by {{book.writer}} </h4>
        <div>{{book.content|linebreaks}}</div>
    </section>

{% endblock %}

templates/book/books.html
{% extends "base.html" %}
{% block title %}
    post
{% endblock %}
{% block content %}

    <div class="flex justify-between px-20 py-10">
        <h4 class="text-2xl font-serif font-bold"> Books I read </h4>
    </div>
    <section class="grid gap-4 px-20">
        {% for book in books %}
            <div>
                <div>
                    <a href="{% url "book:get" book.id %}">
                        <h4 class="text-xl font-serif font-bold text-red-700 underline"> {{book.title}} </h4>
                    </a>
                    <h4 class="text-m font-serif">Writer: {{book.writer}}</h4>    
                </div>
            </div>
        {% endfor %}
    </section>
    <section class="px-20 py-10">
        <div class="col-12">
            <nav>
                <ul class="pagination justify-content-center">
                    {% if books.has_previous %}  
                                               
                        <li class="page-item">
                            <a class="page-link" href="?p={{books.previous_page_number }}">이전으로</a>
                        </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">이전으로</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="#">{{books.number}}/{{books.paginator.num_pages}}</a>
                    </li>
                    {% if books.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?p={{books.next_page_number }}">다음으로</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">다음으로</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </section>

{% endblock %}