book/urls.py
from django.urls import path

from book.views import BookView, list_book

app_name = "book"

urlpatterns = [
    path("<int:book_id>", BookView.as_view(), name="get"),
    path("list", list_book, name="list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


# namespace is used to create url tags to be used in the html files
urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "financial_statement/",
        include("financial_statement.urls", namespace="financial_statement"),
    ),
    path("", include("core.urls", namespace="core")),
    path("valuation/", include("valuation.urls", namespace="valuation")),
    path("user/", include("user.urls", namespace="user")),
    path("company/", include("company.urls", namespace="company")),
    path("notification/", include("notification.urls", namespace="notification")),
    path("post/", include("post.urls", namespace="post")),
    path("book/", include("book.urls", namespace="book")),
]

user/urls.py
from django.urls import path
from user.views import (
    UserView,
)

app_name = "user"

urlpatterns = [
    path("profile", UserView.as_view(), name="profile"),
]

valuation/urls.py
from django.urls import path

from valuation.views import ValuationPage, ValuationTestView, ValuationView

app_name = "valuation"

urlpatterns = [
    path("", ValuationPage, name="valuation_page"),
    path("report/", ValuationTestView.as_view(), name="report"),
]

valuation/models.py
from django.db import models
from user.models import User


class ValuationCategory(models.Model):
    name = models.CharField(max_length=200)


class Valuation(models.Model):
    """Review Model Definition"""

    DCF = "dcf"
    REPRODUCTIOIN_COST = "reproduction_cst"
    OTHER = "other"
    METHOD_CHOICES = (
        (DCF, "DCF"),
        (REPRODUCTIOIN_COST, "Reproduction_cost"),
        (OTHER, "Other"),
    )
    ticker = models.CharField(max_length=10, null=True)
    review = models.TextField()
    method = models.CharField(choices=METHOD_CHOICES, max_length=20, blank=True)
    value = models.FloatField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

valuation/forms.py
from django import forms
from . import models


class ValuationForm(forms.Form):
    DCF = "dcf"
    REPRODUCTIOIN_COST = "reproduction_cst"
    OTHER = "other"
    METHOD_CHOICES = (
        (DCF, "DCF"),
        (REPRODUCTIOIN_COST, "Reproduction_cost"),
        (OTHER, "Other"),
    )

    review = forms.CharField()
    ticker = forms.CharField()
    method = forms.ChoiceField(choices=METHOD_CHOICES)
    value = forms.FloatField()
    formula = forms.CharField()
    financial_statement_id = forms.IntegerField(widget=forms.HiddenInput())

    # financial_statement_id.widget.attrs.update({"readonly": True})
    financial_statement_id.widget.attrs["readonly"] = True

    def clean(self):
        review = self.cleaned_data.get("review")
        ticker = self.cleaned_data.get("ticker")
        method = self.cleaned_data.get("method")
        value = self.cleaned_data.get("value")
        formula = self.cleaned_data.get("formula")

        if "process" in self.data:
            raise forms.ValidationError("The formula is computed.")
        else:
            raise forms.ValidationError("This is submit")

        if ticker == None or value == None or method == None:
            return None

        return self.cleaned_data

valuation/views.py
import json
from email.quoprimime import body_decode

from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.urls.base import reverse
from django.views import View
from django.views.generic.edit import FormView

from Interface.polygon_api import PolygonInterface
from keys import Keys

from . import forms


def ValuationPage(request):
    return render(request, "markdown_template.html")


class ValuationView(FormView):
    template_name = "valuation_template.html"
    form_class = forms.ValuationForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        ticker = form.cleaned_data.get("ticker")
        return super().form_valid(form)


class ValuationTestView(View):
    def get(self, request):
        id = 15
        initial = {
            "financial_statement_id": id,
        }
        form = forms.ValuationForm(initial=initial)
        financial_statement = {}
        return render(
            request,
            "valuation_template.html",
            context={"form": form, "financial_statement": financial_statement},
        )

    def post(self, request):
        form = forms.ValuationForm(request.POST)
        if form.is_valid():
            return redirect(
                reverse("core:home")
            )  # Should be reirected to a success page.
        myDict = dict(request.POST.lists())
        if "process" in myDict:
            print("This is a process")
        if "submit" in myDict:
            print("this is submit")
        return render(request, "valuation_template.html", context={"form": form})

templates/unused/get_financial_statement.html
{% extends "base.html" %}
{% block title %}
    home
{% endblock %}
{% block content %}
    {% for key, val in financial_statement.items %}
        {% if key != "_state" %}
            <h4>{{key}}: {{val}}</h4>  
        {% endif %}
    {% endfor %}
{% endblock %}

templates/unused/get_financial_statement_list.html
{% extends "base.html" %}
{% block title %}
    home
{% endblock %}
{% block content %}
    <div class="bg-white pb-4 px-4 rounded-md w-full">
        <div class="flex justify-between w-full pt-6 ">
            <p class="ml-3"> Fianncial statement table</p>
            <svg width="14" height="4" viewBox="0 0 14 4" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g opacity="0.4">
                    <circle cx="2.19796" cy="1.80139" r="1.38611" fill="#222222"/>
                    <circle cx="11.9013" cy="1.80115" r="1.38611" fill="#222222"/>
                    <circle cx="7.04991" cy="1.80115" r="1.38611" fill="#222222"/>
                </g>
            </svg>

        </div>
        <div class="w-full flex justify-end px-2 mt-2">
            <div class="w-full sm:w-64 inline-block relative ">
                <input type="" name="" class="leading-snug border border-gray-300 block w-full appearance-none bg-gray-100 text-sm text-gray-600 py-1 px-4 pl-8 rounded-lg" placeholder="Search" />

                <div class="pointer-events-none absolute pl-3 inset-y-0 left-0 flex items-center px-2 text-gray-300">

                    <svg class="fill-current h-3 w-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 511.999 511.999">
                        <path d="M508.874 478.708L360.142 329.976c28.21-34.827 45.191-79.103 45.191-127.309C405.333 90.917 314.416 0 202.666 0S0 90.917 0 202.667s90.917 202.667 202.667 202.667c48.206 0 92.482-16.982 127.309-45.191l148.732 148.732c4.167 4.165 10.919 4.165 15.086 0l15.081-15.082c4.165-4.166 4.165-10.92-.001-15.085zM202.667 362.667c-88.229 0-160-71.771-160-160s71.771-160 160-160 160 71.771 160 160-71.771 160-160 160z" />
                    </svg>
                </div>
            </div>
        </div>
        <div class="overflow-x-auto mt-6">

            <table class="table-auto border-collapse w-full">
                <thead>
                    <tr class="rounded-lg text-sm font-medium text-gray-700 text-left" style="font-size: 0.9674rem">
                        <th class="px-4 py-2 bg-gray-200 " style="background-color:#f8f8f8">Name</th>
                        <th class="px-4 py-2 " style="background-color:#f8f8f8">Author</th>
                        <th class="px-4 py-2 " style="background-color:#f8f8f8">Views</th>
                    </tr>
                </thead>
                <tbody class="text-sm font-normal text-gray-700">
                    {% for financial_statement in financial_statements %}
                        <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                            <td class="px-4 py-4">{{financial_statement.ticker}}</td>
                            <td class="px-4 py-4">{{financial_statement.report_period}}</td>
                            <td class="px-4 py-4">{{financial_statement.period}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- <div id="pagination" class="w-full flex justify-center border-t border-gray-100 pt-4 items-center">
            <svg class="h-6 w-6" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g opacity="0.4">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M9 12C9 12.2652 9.10536 12.5196 9.29289 12.7071L13.2929 16.7072C13.6834 17.0977 14.3166 17.0977 14.7071 16.7072C15.0977 16.3167 15.0977 15.6835 14.7071 15.293L11.4142 12L14.7071 8.70712C15.0977 8.31659 15.0977 7.68343 14.7071 7.29289C14.3166 6.90237 13.6834 6.90237 13.2929 7.29289L9.29289 11.2929C9.10536 11.4804 9 11.7348 9 12Z" fill="#2C2C2C"/>
                </g>
            </svg>

            <p class="leading-relaxed cursor-pointer mx-2 text-blue-600 hover:text-blue-600 text-sm">1</p>
            <p class="leading-relaxed cursor-pointer mx-2 text-sm hover:text-blue-600" >2</p>
            <p class="leading-relaxed cursor-pointer mx-2 text-sm hover:text-blue-600"> 3 </p>
            <p class="leading-relaxed cursor-pointer mx-2 text-sm hover:text-blue-600"> 4 </p>
            <svg class="h-6 w-6" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M15 12C15 11.7348 14.8946 11.4804 14.7071 11.2929L10.7071 7.2929C10.3166 6.9024 9.6834 6.9024 9.2929 7.2929C8.9024 7.6834 8.9024 8.3166 9.2929 8.7071L12.5858 12L9.2929 15.2929C8.9024 15.6834 8.9024 16.3166 9.2929 16.7071C9.6834 17.0976 10.3166 17.0976 10.7071 16.7071L14.7071 12.7071C14.8946 12.5196 15 12.2652 15 12Z" fill="#18A0FB"/>
            </svg>

        </div> -->
    </div>

    <style>

    thead tr th:first-child { border-top-left-radius: 10px; border-bottom-left-radius: 10px;}
    thead tr th:last-child { border-top-right-radius: 10px; border-bottom-right-radius: 10px;}

    tbody tr td:first-child { border-top-left-radius: 5px; border-bottom-left-radius: 0px;}
    tbody tr td:last-child { border-top-right-radius: 5px; border-bottom-right-radius: 0px;}


    </style>
{% endblock %}

templates/unused/markdown_template.html
{% extends "base.html" %}
{% block title %}
    home
{% endblock %}
{% block content %}
    <!-- This is an example component -->
    <div>
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Markdown Editor with Codemirror and AlpineJS</title>
            <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" />
            <link rel="stylesheet" href="https://unpkg.com/@tailwindcss/typography@0.2.x/dist/typography.min.css"/>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/codemirror@5.59.2/lib/codemirror.min.css" />
            <link rel="preconnect" href="https://fonts.gstatic.com">
            <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
            <style>
                html { 
                    scroll-behavior: smooth; 
                    font-family: 'Space Grotesk', sans-serif;
                }
                .cursive {
                    font-family: 'Nanum Pen Script', cursive;
                }
                [x-cloak] { display: none; }

                .CodeMirror-focused {   
                    border-radius: .375rem;
                    outline: 2px solid transparent;
                    outline-offset: 2px;
                    --tw-ring-opacity: 0.5;
                    --tw-ring-color: rgba(199, 210, 254, var(--tw-ring-opacity));
                    --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
                    --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(3px + var(--tw-ring-offset-width)) var(--tw-ring-color);
                    box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000);
                }
                .CodeMirror {
                    padding: 0.75rem;
                    font-family: inherit;
                    font-size: inherit;
                    border-bottom-left-radius: .375rem;
                    border-bottom-right-radius: .375rem;
                    --tw-border-opacity: 1;
                    border: 1px solid rgba(209, 213, 219, var(--tw-border-opacity));
                }
                .CodeMirror.CodeMirror-focused {
                    --tw-border-opacity: 1;
                    border-color: rgba(165, 180, 252, var(--tw-border-opacity));
                }

                .cm-s-default .cm-header,
                .cm-s-default .cm-variable-2 {
                    color: rgb(31, 41, 55);
                }
            </style>
        </head>
        <body class="bg-gray-50 antialiased">
            <div class="px-4 max-w-4xl mx-auto min-h-screen py-12">

                <div class="text-3xl lg:text-4xl font-bold tracking-tight mb-4 text-center">
                    <span class="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-green-400 ">
                    Explain your valuation formula and results!
                    </span>
                </div>
            
                <div
                    x-data="markdown()"
                    x-init="
                        convertHtmlToMarkdown();
                        codeMirrorEditor = CodeMirror.fromTextArea($refs.input, {
                            mode: 'markdown',
                            theme: 'default',
                            lineWrapping: true
                        });

                        codeMirrorEditor.setValue(content);
                        codeMirrorEditor.setSize('100%', height);
                        setTimeout(function() {
                            codeMirrorEditor.refresh();
                        }, 1);

                        codeMirrorEditor.on('change', () => content = codeMirrorEditor.getValue())
                    "
                    class="relative"
                    x-cloak
                >
                    <div class="bg-gray-50 border border-b-0 border-gray-300 top-0 left-0 right-0 block rounded-t-md">
                        <button type="button" class="py-2 px-4 inline-block text-gray-400 font-semibold" :class="{ 'text-indigo-600': tab === 'write' }" x-on:click.prevent="tab = 'write'; showConvertedMarkdown = false">Write</button>
                        <button type="button" class="py-2 px-4 inline-block text-gray-400 font-semibold" :class="{ 'text-indigo-600': tab === 'preview' && showConvertedMarkdown === true }" x-on:click.prevent="tab = 'preview'; convertedMarkdown()">Preview</button>
                    </div>

                    <div x-show="! showConvertedMarkdown">
                        <div>
                            <textarea 
                                x-ref="input" 
                                x-model.debounce.750ms="content" 
                                class="hidden"
                                name="content"
                            ></textarea>
                        </div>
                    </div>

                    <div x-show="showConvertedMarkdown">
                        <div x-html="convertedContent" class="w-full prose max-w-none prose-indigo leading-6 rounded-b-md shadow-sm border border-gray-300 p-5 bg-white overflow-y-auto" :style="`height: ${height}; max-width: 100%`"></div>
                    </div>
                </div>

                <div class="mt-6 text-gray-500 text-sm text-center">Created by <a class="text-indigo-500 underline" href="https://twitter.com/mithicher">@mithicher</a>.</div>
            </div>

            <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.0/dist/alpine.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/codemirror@5.59.2/lib/codemirror.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/codemirror@5.59.2/mode/markdown/markdown.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/turndown@7.0.0/dist/turndown.min.js"></script>
            <script src="https://unpkg.com/marked@0.3.6/lib/marked.js"></script>
            <script>
                function markdown() {
                    return {
                        height: '500px',
                        tab: 'write',
                        content: '',
                        showConvertedMarkdown: false,
                        convertedContent: '',
                        convertedMarkdown() {
                            this.showConvertedMarkdown = true;
                            this.convertedContent = marked(this.content, { sanitize: true });
                        },
                        convertHtmlToMarkdown() {
                            turndownService = new TurndownService({
                                headingStyle: 'atx',
                                codeBlockStyle: 'fenced'
                            });

                            this.content = turndownService.turndown(`
                                <h1 id="sample-markdown">Sample Markdown</h1>
                                <p>This is some basic, sample markdown.</p>
                                <h2 id="second-heading">Second Heading</h2>
                                <ul>
                                <li>Unordered lists, and:<ol>
                                <li>One</li>
                                <li>Two</li>
                                <li>Three</li>
                                </ol>
                                </li>
                                <li>More</li>
                                </ul>
                                <blockquote>
                                <p>Blockquote</p>
                                </blockquote>
                                <p>And <strong>bold</strong>, <em>italics</em>, and even <em>italics and later <strong>bold</strong></em>. Even <del>strikethrough</del>. <a href="https://markdowntohtml.com">A link</a> to somewhere.</p>
                                <p>And block highlighting:</p>
                                <pre><code class="lang-js"><span class="hljs-keyword">var</span> foo = <span class="hljs-string">'bar'</span>;

                                <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">baz</span><span class="hljs-params">(s)</span> </span>{
                                <span class="hljs-keyword">return</span> foo + <span class="hljs-string">':'</span> + s;
                                }
                                </code></pre>
                                <p>Or inline code like <code>var foo = &#39;bar&#39;;</code>.</p>
                                <p>Or an image of turtles</p>
                                <p><img src="https://api.timeforkids.com/wp-content/uploads/2020/04/200410016385.jpg?w=1024" alt="turtles"></p>
                                <p>The end ...</p>
                            `);
                        }
                    }
                }
            </script>
        </body>
        </html>
    </div>
{% endblock %}

templates/unused/search.html
{% extends "base.html" %}
{% block title %}
    home
{% endblock %}
{% block content %}
    <section>
        <h4> Ticker result </h4>
        {% for company in ticker_list %}
            <a href="{% url "company:profile" company.id %}">
                {{company.ticker}} : {{company.name}}
            </a>
        {% endfor %}
    </section>
    <section>
        <h4> Name result </h4>
        {% for company in name_list %}
            <a href="{% url "company:profile" company.id %}">
                {{company.ticker}}: {{company.name}}
            </a>
        {% endfor %}
    </section>

{%endblock%}

templates/unused/valuation.html
{% extends "base.html" %}
{% block title %}
    home
{% endblock %}
{% block content %}
    <section class="grid grid-cols-2 gap-4 px-20 py-10">
        <!-- <article class="flex justify-evenly py-10"> -->
        <div>
            <div class="flex justify-between border-b border-gray-400 bg-gray-50">
                <h4 class="text-2xl font-serif"> Valuations</h4>
                <h4 class="text-lg font-serif">more</h4>    
            </div>
            {% for valuation in valuations %}
                <h4 class="font-serif">
                    {{valuation.id}}{{valuation.value}}
                </h4>
            {% endfor %}
        </div>
        <div>
            <div class="flex justify-between border-b border-gray-400 bg-gray-50">
                <h4 class="text-2xl font-serif">Notifications</h4>
                <h4 class="text-lg font-serif">more</h4>    
            </div>            {% for notification in notifications %}
                <h4 class="font-serif">
                    {{notification.company}}{{notifiation.price}}
                </h4>
            {% endfor %}
        </div>

    </section>

{%endblock%}

templates/unused/valuation_template.html
{% extends "base.html" %}
{% block title %}
    home
{% endblock %}
{% block content %}
    <form method="post", action="{% url "valuation:report" %}">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="process" value="process formula" />
        <input type="submit" name="submit" value="Submit" />
    </form>
{%endblock%}