book/urls.py
from django.urls import path

from book.views import BookView, list_book

app_name = "book"

urlpatterns = [
    path("<int:book_id>", BookView.as_view(), name="get"),
    path("list", list_book, name="list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


# namespace is used to create url tags to be used in the html files
urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "financial_statement/",
        include("financial_statement.urls", namespace="financial_statement"),
    ),
    path("", include("core.urls", namespace="core")),
    path("valuation/", include("valuation.urls", namespace="valuation")),
    path("user/", include("user.urls", namespace="user")),
    path("company/", include("company.urls", namespace="company")),
    path("notification/", include("notification.urls", namespace="notification")),
    path("post/", include("post.urls", namespace="post")),
    path("book/", include("book.urls", namespace="book")),
]

post/urls.py
from django.urls import path
from post.views import (
    LogView,
    PostView,
    list_post,
)

app_name = "post"

urlpatterns = [
    path("<int:post_id>", PostView.as_view(), name="get"),
    path("list", list_post, name="list"),
    path("logs", LogView.as_view(), name="logs"),
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="This is the blog of Jiun. Software developer in US.">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>{% block title %}{%endblock%}</title>
</head>
<body class = "text-gray-700">
    <header class="container max-w-full flex items-center justify-between px-6 h-16 border-b border-gray-400 bg-gray-50">
        {% include "partials/nav.html" %}
    </header>
    {% block content %}
    {% endblock %}
    {% include "partials/footer.html" %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}
    home
{% endblock %}
{% block content %}
    <div class="flex justify-between px-20 py-10">
        <h4 class="text-2xl font-serif font-bold"> What's new? </h4>
    </div>
    <section class="grid grid-cols-2 gap-4 px-20">
        {% for post in posts %}
            <div>
                <div>
                    <h4 class="font-thin font-mono">{{post.updated_at}} by Jiun Kim</h4>
                    <h4 class="text-2xl font-serif font-bold"> {{post.title}} </h4>
                    <h4 class="text-lg font-serif">({{post.category}})</h4>    
                </div>
                <div>{{post.content}}...</div>
                <a href="{% url "post:get" post.id %}">
                    <h4 class="text-red-600">Read More</h4>
                </a>
            </div>
        {% endfor %}
    </section>
    <script src="https://unpkg.com/github-calendar@latest/dist/github-calendar.min.js"></script>

    <!-- Optionally, include the theme (if you don't want to struggle to write the CSS) -->
    <link
        rel="stylesheet"
        href="https://unpkg.com/github-calendar@latest/dist/github-calendar-responsive.css"
    />
    
    <div>
        <!-- Prepare a container for your calendar. -->
        <div style="text-align: center;"><strong>나의 GitHub Contribution 그래프</strong></div> 
        <div class="calendar">
            <!-- Loading stuff -->
            Loading data ...
        </div>
    </div>
    
    <script>
        GitHubCalendar(".calendar", "jiun0507", { responsive: true, tooltips: false, global_stats: false}).then(function() {
            // delete the space underneath the module bar which is caused by minheight 
            document.getElementsByClassName('calendar')[0].style.minHeight = "100px";
            // hide more and less legen below the contribution graph
            document.getElementsByClassName('contrib-legend')[0].style.display = "none";
        });
    </script>


{% endblock %}

templates/landing_page.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>{% block title %}{%endblock%}</title>
</head>
<body>
    <div class="flex flex-col h-screen bg-center bg-cover bg-no-repeat bg-gray-100">
        <div class="grid place-items-center w-4/5 mx-auto p-10 my-20 sm:my-auto bg-gray-600 bg-opacity-70 rounded-xl shadow-2xl space-y-5 text-center hover:bg-gray-600 cursor-pointer transition duration-500">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-24 w-24 text-yellow-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <h1 class="text-8xl text-yellow-400 font-semibold uppercase">Jiun Kim's Blog</h1>
            <h2 class="text-2xl text-gray-300">This is a blog to log my interests and works. Look around!</h2>
            <div class="flex flex-wrap mt-10 justify-center space-x-5">
                <a href="{% url "post:logs" %}" class="md:w-32 tracking-wide text-yellow-400 font-bold rounded border-2 border-yellow-400 hover:border-blue-600 hover:bg-blue-600 hover:text-white shadow-md py-2 px-6 inline-flex items-center transition duration-300">
                    <span class="mx-auto">Logs</span>
                </a>

                <a href="{% url "post:list" %}" class="md:w-32 tracking-wide text-yellow-400 font-bold rounded border-2 border-yellow-400 hover:border-blue-500 hover:bg-blue-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center transition duration-300">
                    <span class="mx-auto"> Posts </span>
                </a>
                <a href="{% url "book:list" %}"  class="md:w-32 tracking-wide text-yellow-400 font-bold rounded border-2 border-yellow-400 hover:border-red-600 hover:bg-blue-600 hover:text-white shadow-md py-2 px-6 inline-flex items-center transition duration-300">
                    <span class="mx-auto">Books</span>
                </a>
            </div>
            <div class="flex flex-wrap mt-10 justify-center space-x-5">
                <a href="http://we-dding-dev.herokuapp.com"  class="md:w-32 tracking-wide text-yellow-400 font-bold rounded border-2 border-yellow-400 hover:border-red-600 hover:bg-blue-600 hover:text-white shadow-md py-2 px-6 inline-flex items-center transition duration-300">
                    <span class="mx-auto">Weddew</span>
                </a>
            </div>
        </div>
    </div>

</body>

</html>

templates/out_of_service.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>{% block title %}{%endblock%}</title>
</head>
<body>
    <div class="flex flex-col h-screen bg-center bg-cover bg-no-repeat bg-gray-100">
        <div class="grid place-items-center w-4/5 mx-auto p-10 my-20 sm:my-auto bg-gray-600 bg-opacity-70 rounded-xl shadow-2xl space-y-5 text-center hover:bg-gray-600 cursor-pointer transition duration-500">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-24 w-24 text-yellow-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <h1 class="text-8xl text-yellow-400 font-semibold uppercase">Sorry!</h1>
            <h2 class="text-2xl text-gray-300">{{service}} is currently out of service.</h2>
    
            </div>
        </div>
    </div>

</body>

</html>